name: multipleye3.9
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.9
  - pip==22.3.1
  - psychopy==2022.2.5
  - pip:
      - pygame==2.1.2
      - git+https://github.com/theDebbister/PyGaze # pygaze
      - gooey==1.2.0a0 --no-dependencies
      - re-wx>=0.0.2
      - wxpython>=4.1.0
      - Pillow>=4.3.0
      - psutil>=5.4.2
      - colored>=1.3.93
      - pygtrie>=2.3.3
      - typing-extensions==3.10.0.2
      - mypy-extensions==0.4.3
